hiero.accountId=${HEDERA_ACCOUNT_ID:SHOULD_BE_DEFINED_IN_ENV_FILE}
hiero.privateKey=${HEDERA_PRIVATE_KEY:SHOULD_BE_DEFINED_IN_ENV_FILE}
hiero.network.name=${HEDERA_NETWORK:hedera-testnet}
quarkus.http.port=8081
quarkus.log.category."org.hiero".level=DEBUG