# Hiero Configuration
hiero.accountId=${HEDERA_ACCOUNT_ID:SHOULD_BE_DEFINED_IN_ENV_FILE}
hiero.privateKey=${HEDERA_PRIVATE_KEY:SHOULD_BE_DEFINED_IN_ENV_FILE}
hiero.network.name=${HEDERA_NETWORK:hedera-testnet}

# Quarkus logging
quarkus.log.category."org.hiero".level=DEBUG